FROM ghcr.io/akdev1l/ostree-images/fedora-nvsb:latest

COPY playbooks /tmp
RUN rpm-ostree install -y ansible && \
    ansible-galaxy install -r /tmp/requirements.yml && \
    ansible-playbook /tmp/entrypoint.yml && \
    rm -rf ~/.ansible /var/* ~/.* && \
    ostree container commit

LABEL org.opencontainers.image.source https://github.com/akdev1l/ostree-images
LABEL NAME personal
LABEL VERSION latest
