---
- name: start base image configuration
  hosts: localhost
  tasks:
    - import_tasks: ./tasks/auto-updates.yml
    - import_tasks: ./tasks/install-packages.yml
    - import_tasks: ./tasks/shell-configuration.yml
    - import_tasks: ./tasks/btrfs-snapshots.yml
    - import_tasks: ./tasks/wasabi-sync.yml
