#!/usr/bin/env python

from argparse import ArgumentParser
from logging import (
    basicConfig,
    getLogger,
    INFO
)
from os import mkdir, listdir, path
from subprocess import run
from sys import argv
from time import strftime

basicConfig(
    level=INFO,
    format="%(asctime)s - %(name)s - %(levelname)s - %(message)s"
)
logger = getLogger(path.basename(argv[0]))

def main():

    arg_parser = ArgumentParser()
    arg_parser.add_argument("--instance", help="Passed by systemd, it has the format: ${SRC_PATH}", required=True)
    arg_parser.add_argument("--max", help="Max number of snapshots to keep", default=7, type=int)
    arg_parser.add_argument("--snapshot-format", help="specify format for snapshot names, this gets passed to strfime", default="%Y-%m-%d-%H-%M")
    arg_parser.add_argument("--snapshot-dir", help="specity subdirectory where the snapshots will live [it will be created]", default=".snapshots/daily")

    cli_args = arg_parser.parse_args()

    snapshot_max = cli_args.max
    src_path = cli_args.instance.split("@")[0]
    snapshot_path = path.join(src_path, cli_args.snapshot_dir)
    if not path.exists(snapshot_path):
        mkdir(snapshot_path)

    snapshot_list = get_snapshots(snapshot_path)
    logger.info(f"found {len(snapshot_list)} snapshots [max: {snapshot_max}]")

    snapshots_to_prune = snapshot_list[:-snapshot_max]
    logger.info(f"will prune {len(snapshots_to_prune)}")

    remove_snapshots(snapshots_to_prune)
    create_snapshot(src_path, snapshot_path, cli_args.snapshot_format)

def get_snapshots(snapshot_path):
    top_dir = snapshot_path
    logger.info(f"getting snapshots from {top_dir}")

    subvolumes = listdir(top_dir)
    snapshots = [
        path.join(top_dir, subvolume)
        for subvolume in subvolumes
    ]

    snapshots.sort()
    return snapshots
    
def remove_snapshots(snapshots_to_prune):
    for snapshot in snapshots_to_prune:
        remove_snapshot(snapshot)

def remove_snapshot(snapshot):
    logger.info(f"removing snapshot: {snapshot}")
    btrfs_cmd = [
        'btrfs',
        'subvolume',
        'delete',
        snapshot
    ]

    btrfs_run = run(btrfs_cmd, capture_output=True)

    if btrfs_run.returncode != 0:
        logger.error(f"""command failed: '{" ".join(btrfs_cmd)}'""")
        logger.error(btrfs_run.stderr)
        raise Exception("btrfs command failed")

    logger.info(f"snapshot succesfully removed: {snapshot}")

def create_snapshot(src_path, snapshot_path, snapshot_format="%Y-%m-%d-%H-%M"):
    new_snapshot_path = path.join(snapshot_path, strftime(snapshot_format))
    logger.info(f"creating snapshot: {src_path} -> {new_snapshot_path}")

    if path.exists(new_snapshot_path):
        logger.warning(f"snapshot path '{new_snapshot_path}' already exists. skipping.")
        return
    
    btrfs_cmd = [
        'btrfs',
        'subvolume',
        'snapshot',
        src_path,
        new_snapshot_path
    ]

    btrfs_run = run(btrfs_cmd, capture_output=True)

    if btrfs_run.returncode != 0:
        logger.error(f"""command failed: '{" ".join(btrfs_cmd)}'""")
        logger.error(btrfs_run.stderr)
        raise Exception("btrfs command failed")

    logger.info(f"snapshot created {new_snapshot_path}")


if __name__ == "__main__":
    main()
