set number
set relativenumber

set softtabstop=4
set tabstop=4
set expandtab
set shiftwidth=4

autocmd FileType yml setlocal tabstop=2 softtabstop=2 shiftwidth=2 expandtab
augroup templates
    autocmd BufNewFile *.py 0r ~/.config/vim/templates/python-skel.vim
augroup END
