#!/bin/bash
#
# This script syncs the home directory with a wasabi s3 bucket
# by using rclone.
    
set -x
    

main() {

    rclone sync "$HOME" wasabi:xyz.akdev.private/home \
        --exclude '/.local/share/containers/**' \
        --exclude '/.local/share/flatpak/**' \
        --exclude '/.cache/**' \
        --exclude '/.var/app/**' \
        --exclude '/.snapshots/**' \
        --exclude '/.ssh/**' \
        --drive-chunk-size 128M \
        -P

}

main "$@"
