#!/bin/bash
#
# This script syncs the home directory with a wasabi s3 bucket
# by using rclone.
    
set -x
    

main() {

    rclone sync "$HOME" wasabi-home: \
        --exclude '/.*/**' \
        --exclude '/**.iso' \
        --drive-chunk-size 128M \
        -P
}

main "$@"
