#
# .zshrc is sourced in interactive shells.
# It should contain commands to set up aliases,
# functions, options, key bindings, etc.
#

autoload -U compinit
compinit

#allow tab completion in the middle of a word
setopt COMPLETE_IN_WORD

# Path to your oh-my-zsh installation.
export ZSH="/etc/oh-my-zsh"
export ZSH_THEME="gianu"
export CASE_SENSITIVE="true"
export DISABLE_MAGIC_FUNCTIONS="true"
setopt HIST_IGNORE_SPACE

source $ZSH/oh-my-zsh.sh

# User configuration
export MAKEOPTS="-j$(nproc)"
export EDITOR=vim
export VISUAL=vim
export SSH_AUTH_SOCK="$(gpgconf --list-dirs agent-ssh-socket)"

# Here we make things pretty
# Many taken from https://wiki.archlinux.org/title/Color_output_in_console
export LS_COLORS="$(vivid generate molokai)"
export MANPAGER="less -R --use-color -Dd+r -Du+b"
export LESSOPEN='| /usr/bin/source-highlight-esc.sh %s'
export LESS='-R --use-color -Dd+r$Du+b$'

alias ls='ls --color=tty --group-directories-first'
alias diff='diff -u --color=auto'
alias ip='ip -color=auto'
