---
- name: remove unnecessary packages from base image
  community.general.rpm_ostree_pkg:
    state: absent
    name:
      - firefox
      - firefox-langpacks

- name: install packages with rpm-ostree
  community.general.rpm_ostree_pkg:
    state: present
    name:
      - libvirt
      - virt-manager
      - qemu-kvm
      - virt-viewer
      - zsh
      - git
      - tmux
      - vim
      - ripgrep
      - fira-code-fonts
      - rclone
      - pam_yubico
      - yubikey-manager-qt
      - yubikey-manager
      - yubikey-personalization-gui
      - ykclient
      - ykpers
      - pam-u2f
      - pamu2fcfg
      - keepassxc
      - borgbackup
      - distrobox
      - python3-lxml
      - swtpm
      - wl-clipboard
      - gvfs-nfs
      - konsole5
      - fzf
      - python3-pip
      - source-highlight
      - aria2
      - aspell
      - nodejs
      - iotop
      - most
      - bat
      - fd-find
      - java-latest-openjdk
      - cmake
      - moby-engine
      - fedpkg
      - policycoreutils-newrole

- name: truncate fedora-flathub filter
  copy:
    dest: /usr/share/flatpak/fedora-flathub.filter
    content: ""
