---
- name: install packages with rpm-ostree
  community.general.rpm_ostree_pkg:
    state: present
    name:
      - libvirt
      - virt-manager
      - qemu-kvm
      - virt-viewer
      - zsh
      - git
      - tmux
      - vim
      - ripgrep
      - fira-code-fonts
      - rclone
      - fedora-flathub-remote

- name: truncate fedora-flathub filter
  copy:
    dest: /usr/share/flatpak/fedora-flathub.filter
    content: ""
