---
- name: remove unnecessary packages from base image
  community.general.rpm_ostree_pkg:
    state: absent
    name:
      - firefox
      - firefox-langpacks
      - toolbox

- name: install packages with rpm-ostree
  community.general.rpm_ostree_pkg:
    state: present
    name:
      - libvirt
      - virt-manager
      - qemu-kvm
      - virt-viewer
      - zsh
      - git
      - tmux
      - vim
      - ripgrep
      - fira-code-fonts
      - rclone
      - fedora-flathub-remote
      - yubikey-manager-qt
      - yubikey-manager
      - ykclient
      - keepassxc
      - borgbackup
      - distrobox
      - python3-lxml

- name: truncate fedora-flathub filter
  copy:
    dest: /usr/share/flatpak/fedora-flathub.filter
    content: ""
