---
- name: remove unnecessary packages from base image
  community.general.rpm_ostree_pkg:
    state: absent
    name:
      - firefox
      - firefox-langpacks

- name: install packages with rpm-ostree
  community.general.rpm_ostree_pkg:
    state: present
    name:
      - libvirt
      - virt-manager
      - qemu-kvm
      - virt-viewer
      - zsh
      - git
      - tmux
      - vim
      - ripgrep
      - fira-code-fonts
      - rclone
      - yubikey-manager-qt
      - yubikey-manager
      - ykclient
      - yubioath-desktop
      - keepassxc

- name: make sure flatpak installations.d exists
  file:
    path: /etc/flatpak/installations.d
    state: directory

- name: create flatpak extra installation to allow flatpak installation
  copy:
    src: flatpak-extra.conf
    dest: /etc/flatpak/installations.d/extra.conf

- name: install flathub remote in extra installation
  shell: |
    flatpak --installation=extra remote-add flathub https://flathub.org/repo/flathub.flatpakrepo

- name: install flatpak applications from flathub
  shell: |
    flatpak install -y {{item|quote}}
  loop:
    - org.mozilla.firefox
    - com.discordapp.Discord
    - com.github.wwmm.easyeffects
    - com.valvesoftware.Steam
    - com.valvesoftware.Steam.CompatibilityTool.Proton
    - com.valvesoftware.Steam.CompatibilityTool.Proton-GE
    - com.valvesoftware.Steam.CompatibilityTool.Proton-Exp
