---
- name: install vim-plug
  shell:
    curl -fLo /usr/share/vim/vimfiles/plug.vim --create-dirs \
      https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

- name: drop in vimrc
  copy:
    src: vimrc
    mode: '0644'
    dest: "/etc/vimrc.local"

- name: install tmux-themepack
  git:
    repo: https://github.com/jimeh/tmux-themepack.git
    dest: /etc/tmux-themepack

- name: configure tmux
  copy:
    src: tmux.conf
    dest: /etc/tmux.conf
    mode: '0644'

- name: install oh-my-zsh
  shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" --unattended
  environment:
    ZSH: /etc/oh-my-zsh

- name: install zsh-syntax-highlighting
  git:
    repo: "{{ item.repo }}"
    dest: "/etc/oh-my-zsh/plugins/{{ item.name }}"
  loop:
    - repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
      name: zsh-syntax-highlighting
    - repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
      name: zsh-autosuggestions

- name: drop custom shell environment
  copy:
    src: zshrc
    dest: /etc/skel/.zshrc
