ARG KERNEL_VERSION="6.0.10-300.fc37.x86_64"
ARG RPMFUSION_FREE="https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-37.noarch.rpm"
ARG RPMFUSION_NON_FREE="https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-37.noarch.rpm"

FROM fedora:37
ARG KERNEL_VERSION
ARG RPMFUSION_FREE
ARG RPMFUSION_NON_FREE

RUN dnf install -y $RPMFUSION_FREE $RPMFUSION_NON_FREE fedora-repos-archive && \
    dnf install -y mock xorg-x11-drv-nvidia{,-cuda} binutils kernel-devel-$KERNEL_VERSION kernel-$KERNEL_VERSION && \
    akmods --force

FROM ghcr.io/cgwalters/fedora-silverblue:37
ARG KERNEL_VERSION
ARG RPMFUSION_FREE
ARG RPMFUSION_NON_FREE

# See https://pagure.io/releng/issue/11047 for final location
# Copy kmod rpm from previous stage
COPY --from=0 /var/cache/akmods/nvidia /tmp/nvidia

RUN rpm-ostree install ${RPMFUSION_FREE} ${RPMFUSION_NON_FREE} && \
    rpm-ostree install xorg-x11-drv-nvidia{,-cuda} kernel-${KERNEL_VERSION} && \
    rpm-ostree install /tmp/nvidia/*${KERNEL_VERSION}*.rpm && \
    rm -rf /var/* && rm -rf /tmp/nvidia && \
    ostree container commit

LABEL org.opencontainers.image.source https://github.com/akdev1l/ostree-images
LABEL NAME fedora-nvsb
LABEL VERSION latest
