name: build silverblue ostree container images

on:
  schedule:
    - cron: '45 5 * * *'
      #push:
    #branches: [ "master" ]

env:
  REGISTRY_USER: ${{ github.actor }}
  REGISTRY_PASSWORD: ${{ github.token }}
  IMAGE_TAGS: latest
  IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Log in to ghcr.io
      uses: redhat-actions/podman-login@v1
      with:
        username: ${{ env.REGISTRY_USER }}
        password: ${{ env.REGISTRY_PASSWORD }}
        registry: ${{ env.IMAGE_REGISTRY }}

    - name: publish ostree-images to container repository
      run: IMAGE_TAGS="${IMAGE_TAGS} $(date '+%Y%m%d')" ./publish-all.sh
