name: build nvidia-silverblue ostree oci image

on:
  schedule:
    - cron: '45 5 * * *'
  push:
    branches: [ "master" ]

env:
  REGISTRY_USER: ${{ github.actor }}
  REGISTRY_PASSWORD: ${{ github.token }}
  IMAGE_NAME: nvidia-silverblue
  IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}
  IMAGE_TAGS: latest ${{ github.sha }}

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: build container image
      id: podman_build
      uses: redhat-actions/buildah-build@v2
      with:
        containerfiles: ./images/fedora-nvsb/Containerfile
        image: ${{ env.IMAGE_NAME }}
        tags: ${{ env.IMAGE_TAGS }}
        oci: true

    - name: push to ghcr
      uses: redhat-actions/push-to-registry@v2
      id: podman_push
      with:
        image: ${{ steps.podman_build.outputs.image }} 
        tags: ${{ steps.podman_build.outputs.tags }}
        registry: ${{ env.IMAGE_REGISTRY }}
        username: ${{ env.REGISTRY_USER }}
        password: ${{ env.REGISTRY_PASSWORD }}
